module.exports = {
    tokenMissing: "authorization header missing or invalid",
    role: "invalid role",
    unauthorized: "unauthorized",
    invalidToken: "invalid token",
    false: "false",
    true: "true",
    notFound: "not found",
    badRequest: "bad request",
    internalServerError: "internal Server Error",
    loginSuccess: "login successfully",
    loginFailed: "unable to login",
    registeredSuccess: "registered successfully",
    registeredFailed: "unable to register",
    uploadSuccess: "file uploaded successfully",
    uploadFailed: "failed to upload",
    noFile: "no file uploaded",
    editProductSuccess: "product edited successfully",
    notPurchased: "unable to purchase",
    notUpdated: "unable to update",
    listProducts: "product fetched successfully",
    notFetched: "unable to fetch",
    fieldsRequired: "fields required",
    orderCreated: "purchased successfully",
    orderUpdated: "order updated successfully",
    orderDeleted: "order deleted successfully",
    notDeleted: "unable to delete",
    listOrders: "order fetched successfully",
    exists: "already exists",
    email: "invalid email",
    password: "invalid password",
    productId: "invalid product ID",
    user: "invalid user ID",
    mailSent: "mail sent successfully",
    insufficient: "insufficient product quantity"
};